export const options = [
    { value: "Afganisztán", label: "Afganisztán" },
    { value: "Albánia", label: "Albánia" },
    { value: "Algéria", label: "Algéria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Argentína", label: "Argentína" },
    { value: "Ausztrália", label: "Ausztrália" },
    { value: "Ausztria", label: "Ausztria" },
    { value: "Azerbajdzsán", label: "Azerbajdzsán" },
    { value: "Bahama-szigetek", label: "Bahama-szigetek" },
    { value: "Bahrein", label: "Bahrein" },
    { value: "Banglades", label: "Banglades" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bhután", label: "Bhután" },
    { value: "Bissau-Guinea", label: "Bissau-Guinea" },
    { value: "Bolívia", label: "Bolívia" },
    { value: "Bosznia-Hercegovina", label: "Bosznia-Hercegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazília", label: "Brazília" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgária", label: "Bulgária" },
    { value: "BurkinaFaso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Chile", label: "Chile" },
    { value: "Ciprus", label: "Ciprus" },
    { value: "Comore-szigetek", label: "Comore-szigetek" },
    { value: "CostaRica", label: "Costa Rica" },
    { value: "Csád", label: "Csád" },
    { value: "Csehország", label: "Csehország" },
    { value: "Dánia", label: "Dánia" },
    { value: "Dél-afrikai Köztársaság", label: "Dél-afrikai Köztársaság" },
    { value: "Dél-Korea", label: "Dél-Korea" },
    { value: "Dominikai Közösség", label: "Dominikai Közösség" },
    { value: "Dominikai Köztársaság", label: "Dominikai Köztársaság" },
    { value: "Dzsibuti", label: "Dzsibuti" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egyenlítői-Guinea", label: "Egyenlítői-Guinea" },
    { value: "Egyesült Arab Emírségek", label: "Egyesült Arab Emírségek" },
    { value: "Egyesült Királyság", label: "Egyesült Királyság" },
    { value: "Egyiptom", label: "Egyiptom" },
    { value: "Elefántcsontpart", label: "Elefántcsontpart" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Etiópia", label: "Etiópia" },
    { value: "Észak-Korea", label: "Észak-Korea" },
    { value: "Észtország", label: "Észtország" },
    { value: "Fehéroroszország", label: "Fehéroroszország" },
    { value: "Fidzsi", label: "Fidzsi" },
    { value: "Finnország", label: "Finnország" },
    { value: "Franciaország", label: "Franciaország" },
    { value: "Fülöp-szigetek", label: "Fülöp-szigetek" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Ghána", label: "Ghána" },
    { value: "Görögország", label: "Görögország" },
    { value: "Grenada", label: "Grenada" },
    { value: "Grúzia", label: "Grúzia" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Hollandia", label: "Hollandia" },
    { value: "Honduras", label: "Honduras" },
    { value: "Horvátország", label: "Horvátország" },
    { value: "India", label: "India" },
    { value: "Indonézia", label: "Indonézia" },
    { value: "Irak", label: "Irak" },
    { value: "Irán", label: "Irán" },
    { value: "Izland", label: "Izland" },
    { value: "Izrael", label: "Izrael" },
    { value: "Írország", label: "Írország" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japán", label: "Japán" },
    { value: "Jemen", label: "Jemen" },
    { value: "Jordánia", label: "Jordánia" },
    { value: "Kambodzsa", label: "Kambodzsa" },
    { value: "Kamerun", label: "Kamerun" },
    { value: "Kanada", label: "Kanada" },
    { value: "Katar", label: "Katar" },
    { value: "Kazahsztán", label: "Kazahsztán" },
    { value: "Kelet-Timor", label: "Kelet-Timor" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kína", label: "Kína" },
    { value: "Kirgizisztán", label: "Kirgizisztán" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kolumbia", label: "Kolumbia" },
    {
      value: "Kongói Demokratikus Köztársaság",
      label: "Kongói Demokratikus Köztársaság",
    },
    { value: "Kongói Köztársaság", label: "Kongói Köztársaság" },
    { value: "Közép-Afrika", label: "Közép-Afrika" },
    { value: "Kuba", label: "Kuba" },
    { value: "Kuvait", label: "Kuvait" },
    { value: "Laosz", label: "Laosz" },
    { value: "Lengyelország", label: "Lengyelország" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Lettország", label: "Lettország" },
    { value: "Libanon", label: "Libanon" },
    { value: "Libéria", label: "Libéria" },
    { value: "Líbia", label: "Líbia" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Litvánia", label: "Litvánia" },
    { value: "Luxemburg", label: "Luxemburg" },
    { value: "Észak-Macedónia", label: "Észak-Macedónia" },
    { value: "Madagaszkár", label: "Madagaszkár" },
    { value: "Magyarország", label: "Magyarország" },
    { value: "Malajzia", label: "Malajzia" },
    { value: "Malawi", label: "Malawi" },
    { value: "Maldív-szigetek", label: "Maldív-szigetek" },
    { value: "Mali", label: "Mali" },
    { value: "Marokkó", label: "Marokkó" },
    { value: "Marshall-szigetek", label: "Marshall-szigetek" },
    { value: "Mauritánia", label: "Mauritánia" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Málta", label: "Málta" },
    { value: "Mexikó", label: "Mexikó" },
    { value: "Mikronézia", label: "Mikronézia" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongólia", label: "Mongólia" },
    { value: "Montenegró", label: "Montenegró" },
    { value: "Mozambik", label: "Mozambik" },
    { value: "Mianmar", label: "Mianmar" },
    { value: "Namíbia", label: "Namíbia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepál", label: "Nepál" },
    { value: "Németország", label: "Németország" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigéria", label: "Nigéria" },
    { value: "Norvégia", label: "Norvégia" },
    { value: "Olaszország", label: "Olaszország" },
    { value: "Omán", label: "Omán" },
    { value: "Oroszország", label: "Oroszország" },
    { value: "Örményország", label: "Örményország" },
    { value: "Pakisztán", label: "Pakisztán" },
    { value: "Palau", label: "Palau" },
    { value: "Panama", label: "Panama" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "PápuaÚj-Guinea", label: "Pápua-Új-Guinea" },
    { value: "Peru", label: "Peru" },
    { value: "Portugália", label: "Portugália" },
    { value: "Románia", label: "Románia" },
    { value: "Ruanda", label: "Ruanda" },
    { value: "SaintLucia", label: "Saint Lucia" },
    { value: "Salamon-szigetek", label: "Salamon-szigetek" },
    { value: "Salvador", label: "Salvador" },
    { value: "SanMarino", label: "San Marino" },
    { value: "Seychelle-szigetek", label: "Seychelle-szigetek" },
    { value: "SierraLeone", label: "Sierra Leone" },
    { value: "Spanyolország", label: "Spanyolország" },
    { value: "SríLanka", label: "Srí Lanka" },
    { value: "Suriname", label: "Suriname" },
    { value: "Svájc", label: "Svájc" },
    { value: "Svédország", label: "Svédország" },
    { value: "Szamoa", label: "Szamoa" },
    { value: "Szaúd-Arábia", label: "Szaúd-Arábia" },
    { value: "Szenegál", label: "Szenegál" },
    { value: "Szerbia", label: "Szerbia" },
    { value: "Szingapúr", label: "Szingapúr" },
    { value: "Szíria", label: "Szíria" },
    { value: "Szlovákia", label: "Szlovákia" },
    { value: "Szlovénia", label: "Szlovénia" },
    { value: "Szomália", label: "Szomália" },
    { value: "Szudán", label: "Szudán" },
    { value: "Szváziföld", label: "Szváziföld" },
    { value: "Tádzsikisztán", label: "Tádzsikisztán" },
    { value: "Tanzánia", label: "Tanzánia" },
    { value: "Thaiföld", label: "Thaiföld" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Törökország", label: "Törökország" },
    { value: "Tunézia", label: "Tunézia" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Türkmenisztán", label: "Türkmenisztán" },
    { value: "USA", label: "Egyesült Államok" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukrajna", label: "Ukrajna" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Új-Zéland", label: "Új-Zéland" },
    { value: "Üzbegisztán", label: "Üzbegisztán" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Vatikán", label: "Vatikán" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnám", label: "Vietnám" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
    { value: "Zöld-foki Köztársaság", label: "Zöld-foki Köztársaság" },
  ];